import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// ── Styles ─────────────────────────────────────────────────────
const styles = {
    overlay: {
        position: 'fixed',
        inset: 0,
        zIndex: 9999,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'var(--bg-overlay)',
        backdropFilter: 'blur(6px)',
        WebkitBackdropFilter: 'blur(6px)',
        animation: 'fadeIn 0.3s var(--ease-smooth)',
    },
    card: {
        background: 'var(--bg-surface)',
        border: '1px solid var(--danger)',
        borderRadius: 'var(--radius-lg)',
        padding: 'var(--sp-8)',
        maxWidth: 560,
        width: '90%',
        maxHeight: '80vh',
        overflow: 'auto',
        boxShadow: '0 8px 32px rgba(0,0,0,0.5), 0 0 0 1px var(--danger-muted)',
        animation: 'modalIn 0.3s var(--ease-smooth)',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--sp-3)',
        marginBottom: 'var(--sp-5)',
    },
    iconCircle: {
        width: 40,
        height: 40,
        borderRadius: '50%',
        background: 'var(--danger-muted)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    icon: {
        color: 'var(--danger)',
        fontSize: 20,
        fontWeight: 700,
    },
    title: {
        fontSize: 18,
        fontWeight: 700,
        color: 'var(--text-primary)',
        fontFamily: 'var(--font-sans)',
    },
    subtitle: {
        fontSize: 12,
        color: 'var(--text-tertiary)',
        fontFamily: 'var(--font-sans)',
    },
    message: {
        fontSize: 14,
        color: 'var(--text-secondary)',
        lineHeight: 1.6,
        marginBottom: 'var(--sp-5)',
        fontFamily: 'var(--font-sans)',
        wordBreak: 'break-word',
    },
    stackContainer: {
        background: 'var(--bg-elevated)',
        border: '1px solid var(--border-subtle)',
        borderRadius: 'var(--radius-sm)',
        padding: 'var(--sp-4)',
        marginBottom: 'var(--sp-5)',
        maxHeight: 200,
        overflow: 'auto',
    },
    stackLabel: {
        fontSize: 10,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: '0.06em',
        color: 'var(--text-tertiary)',
        marginBottom: 'var(--sp-2)',
        fontFamily: 'var(--font-sans)',
    },
    stackTrace: {
        fontSize: 11,
        fontFamily: 'var(--font-mono)',
        color: 'var(--text-tertiary)',
        lineHeight: 1.6,
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-all',
        margin: 0,
    },
    dismissBtn: {
        display: 'block',
        width: '100%',
        padding: 'var(--sp-3)',
        borderRadius: 'var(--radius-sm)',
        fontSize: 13,
        fontWeight: 600,
        cursor: 'pointer',
        border: 'none',
        background: 'var(--bg-elevated)',
        color: 'var(--text-secondary)',
        transition: 'all 0.15s var(--ease-smooth)',
        fontFamily: 'var(--font-sans)',
        textAlign: 'center',
    },
};
// ── Component ──────────────────────────────────────────────────
export function ErrorOverlay({ error, showStack = false, onDismiss }) {
    const errorMessage = typeof error === 'string' ? error : error.message;
    const errorStack = typeof error === 'string' ? null : error.stack;
    return (_jsx("div", { style: styles.overlay, role: "alert", children: _jsxs("div", { style: styles.card, children: [_jsxs("div", { style: styles.header, children: [_jsx("div", { style: styles.iconCircle, children: _jsx("span", { style: styles.icon, children: "!" }) }), _jsxs("div", { children: [_jsx("div", { style: styles.title, children: "Something went wrong" }), _jsx("div", { style: styles.subtitle, children: "An unexpected error occurred" })] })] }), _jsx("div", { style: styles.message, children: errorMessage }), showStack && errorStack && (_jsxs("div", { style: styles.stackContainer, children: [_jsx("div", { style: styles.stackLabel, children: "Stack Trace" }), _jsx("pre", { style: styles.stackTrace, children: errorStack })] })), _jsx("button", { style: styles.dismissBtn, onClick: onDismiss, children: "Dismiss and return to Dashboard" })] }) }));
}
